import {createSlice} from "@reduxjs/toolkit"
import {useSelector, useDispatch} from "react-redux"
import type {StoreState, StoreDispatch} from "../store"
import * as Tone from "tone"
import {Midi} from "@tonejs/midi"
import placeholder from "../assets/images/placeholder.png"

const playbackSlice = createSlice({
    name: "playback",
    initialState: {
        reverse: false,
        pitch: 0,
        speed: 1,
        volume: 1,
        muted: false,
        loop: false,
        abloop: false,
        loopStart: 0,
        loopEnd: 100,
        preservesPitch: false,
        duration: 0,
        song: "",
        songName: "No title",
        songCover: placeholder,
        songUrl: "",
        editCode: "",
        download: "",
        playHover: false,
        volumeHover: false,
        sampleRate: 100,
        reverbMix: 0,
        reverbDecay: 1.5,
        delayMix: 0,
        delayTime: 0.25,
        delayFeedback: 0.5,
        phaserMix: 0,
        phaserFrequency: 1,
        lowpassCutoff: 100,
        highpassCutoff: 0,
        filterResonance: 6,
        filterSlope: 0,
        highshelfCutoff: 70,
        highshelfGain: 0,
        lowshelfCutoff: 30,
        lowshelfGain: 0,
        midi: false,
        midiFile: null as unknown as Midi,
        midiDuration: 0,
        bpm: 0,
        wave: "square",
        basicWave: "square",
        waveType: "basic",
        attack: 0.02,
        decay: 0.5,
        sustain: 0.3,
        release: 0.5,
        poly: true,
        portamento: 0,
        mouseFlag: false,
        savedLoop: [0, 100],
        pitchLFO: false,
        pitchLFORate: 1,
        stepFlag: false,
        splitBands: false,
        splitBandFreq: 500,
        previousVolume: 0,
        paused: false,
        seekTo: null as number | null,
        secondsProgress: 0,
        progress: 0,
        dragProgress: null as number | null,
        dragging: false,
        abDragging: false
    },
    reducers: {
        setReverse: (state, action) => {state.reverse = action.payload},
        setPitch: (state, action) => {state.pitch = action.payload},
        setSpeed: (state, action) => {state.speed = action.payload},
        setVolume: (state, action) => {state.volume = action.payload},
        setMuted: (state, action) => {state.muted = action.payload},
        setLoop: (state, action) => {state.loop = action.payload},
        setABLoop: (state, action) => {state.abloop = action.payload},
        setLoopStart: (state, action) => {state.loopStart = action.payload},
        setLoopEnd: (state, action) => {state.loopEnd = action.payload},
        setPreservesPitch: (state, action) => {state.preservesPitch = action.payload},
        setDuration: (state, action) => {state.duration = action.payload},
        setSong: (state, action) => {state.song = action.payload},
        setSongName: (state, action) => {state.songName = action.payload},
        setSongCover: (state, action) => {state.songCover = action.payload},
        setSongUrl: (state, action) => {state.songUrl = action.payload},
        setEditCode: (state, action) => {state.editCode = action.payload},
        setDownload: (state, action) => {state.download = action.payload},
        setPlayHover: (state, action) => {state.playHover = action.payload},
        setVolumeHover: (state, action) => {state.volumeHover = action.payload},
        setSampleRate: (state, action) => {state.sampleRate = action.payload},
        setReverbMix: (state, action) => {state.reverbMix = action.payload},
        setReverbDecay: (state, action) => {state.reverbDecay = action.payload},
        setDelayMix: (state, action) => {state.delayMix = action.payload},
        setDelayTime: (state, action) => {state.delayTime = action.payload},
        setDelayFeedback: (state, action) => {state.delayFeedback = action.payload},
        setPhaserMix: (state, action) => {state.phaserMix = action.payload},
        setPhaserFrequency: (state, action) => {state.phaserFrequency = action.payload},
        setLowpassCutoff: (state, action) => {state.lowpassCutoff = action.payload},
        setHighpassCutoff: (state, action) => {state.highpassCutoff = action.payload},
        setFilterResonance: (state, action) => {state.filterResonance = action.payload},
        setFilterSlope: (state, action) => {state.filterSlope = action.payload},
        setHighshelfCutoff: (state, action) => {state.highshelfCutoff = action.payload},
        setHighshelfGain: (state, action) => {state.highshelfGain = action.payload},
        setLowshelfCutoff: (state, action) => {state.lowshelfCutoff = action.payload},
        setLowshelfGain: (state, action) => {state.lowshelfGain = action.payload},
        setMidi: (state, action) => {state.midi = action.payload},
        setMidiFile: (state, action) => {state.midiFile = action.payload},
        setMidiDuration: (state, action) => {state.midiDuration = action.payload},
        setBpm: (state, action) => {state.bpm = action.payload},
        setWave: (state, action) => {state.wave = action.payload},
        setBasicWave: (state, action) => {state.basicWave = action.payload},
        setWaveType: (state, action) => {state.waveType = action.payload},
        setAttack: (state, action) => {state.attack = action.payload},
        setDecay: (state, action) => {state.decay = action.payload},
        setSustain: (state, action) => {state.sustain = action.payload},
        setRelease: (state, action) => {state.release = action.payload},
        setPoly: (state, action) => {state.poly = action.payload},
        setPortamento: (state, action) => {state.portamento = action.payload},
        setMouseFlag: (state, action) => {state.mouseFlag = action.payload},
        setSavedLoop: (state, action) => {state.savedLoop = action.payload},
        setPitchLFO: (state, action) => {state.pitchLFO = action.payload},
        setPitchLFORate: (state, action) => {state.pitchLFORate = action.payload},
        setStepFlag: (state, action) => {state.stepFlag = action.payload},
        setSplitBands: (state, action) => {state.splitBands = action.payload},
        setSplitBandFreq: (state, action) => {state.splitBandFreq = action.payload},
        setPreviousVolume: (state, action) => {state.previousVolume = action.payload},
        setPaused: (state, action) => {state.paused = action.payload},
        setSeekTo: (state, action) => {state.seekTo = action.payload},
        setSecondsProgress: (state, action) => {state.secondsProgress = action.payload},
        setProgress: (state, action) => {state.progress = action.payload},
        setDragProgress: (state, action) => {state.dragProgress = action.payload},
        setDragging: (state, action) => {state.dragging = action.payload},
        setABDragging: (state, action) => {state.abDragging = action.payload}
    }
})

const {
    setReverse, setPitch, setSpeed, setVolume, setMuted, setLoop, setABLoop,
    setLoopStart, setLoopEnd, setPreservesPitch, setDuration, setSong,
    setSongName, setSongCover, setSongUrl, setEditCode, setDownload,
    setPlayHover, setVolumeHover, setSampleRate, setReverbMix,
    setReverbDecay, setDelayMix, setDelayTime, setDelayFeedback, setPhaserMix,
    setPhaserFrequency, setLowpassCutoff, setHighpassCutoff, setFilterResonance,
    setFilterSlope, setHighshelfCutoff, setHighshelfGain, setLowshelfCutoff,
    setLowshelfGain, setMidi, setMidiFile, setMidiDuration, setBpm, setWave,
    setAttack, setDecay, setSustain, setRelease, setPoly, setPortamento,
    setMouseFlag, setSavedLoop, setPitchLFO, setPitchLFORate, setStepFlag,
    setSplitBands, setSplitBandFreq, setPreviousVolume, setPaused, setSeekTo,
    setSecondsProgress, setProgress, setDragProgress, setDragging, setBasicWave, 
    setWaveType, setABDragging
} = playbackSlice.actions

export const usePlaybackSelector = () => {
    const selector = useSelector.withTypes<StoreState>()
    return {
        reverse: selector((state) => state.playback.reverse),
        pitch: selector((state) => state.playback.pitch),
        speed: selector((state) => state.playback.speed),
        volume: selector((state) => state.playback.volume),
        muted: selector((state) => state.playback.muted),
        loop: selector((state) => state.playback.loop),
        abloop: selector((state) => state.playback.abloop),
        loopStart: selector((state) => state.playback.loopStart),
        loopEnd: selector((state) => state.playback.loopEnd),
        preservesPitch: selector((state) => state.playback.preservesPitch),
        duration: selector((state) => state.playback.duration),
        song: selector((state) => state.playback.song),
        songName: selector((state) => state.playback.songName),
        songCover: selector((state) => state.playback.songCover),
        songUrl: selector((state) => state.playback.songUrl),
        editCode: selector((state) => state.playback.editCode),
        download: selector((state) => state.playback.download),
        playHover: selector((state) => state.playback.playHover),
        volumeHover: selector((state) => state.playback.volumeHover),
        sampleRate: selector((state) => state.playback.sampleRate),
        reverbMix: selector((state) => state.playback.reverbMix),
        reverbDecay: selector((state) => state.playback.reverbDecay),
        delayMix: selector((state) => state.playback.delayMix),
        delayTime: selector((state) => state.playback.delayTime),
        delayFeedback: selector((state) => state.playback.delayFeedback),
        phaserMix: selector((state) => state.playback.phaserMix),
        phaserFrequency: selector((state) => state.playback.phaserFrequency),
        lowpassCutoff: selector((state) => state.playback.lowpassCutoff),
        highpassCutoff: selector((state) => state.playback.highpassCutoff),
        filterResonance: selector((state) => state.playback.filterResonance),
        filterSlope: selector((state) => state.playback.filterSlope),
        highshelfCutoff: selector((state) => state.playback.highshelfCutoff),
        highshelfGain: selector((state) => state.playback.highshelfGain),
        lowshelfCutoff: selector((state) => state.playback.lowshelfCutoff),
        lowshelfGain: selector((state) => state.playback.lowshelfGain),
        midi: selector((state) => state.playback.midi),
        midiFile: selector((state) => state.playback.midiFile),
        midiDuration: selector((state) => state.playback.midiDuration),
        bpm: selector((state) => state.playback.bpm),
        wave: selector((state) => state.playback.wave),
        basicWave: selector((state) => state.playback.basicWave),
        waveType: selector((state) => state.playback.waveType),
        attack: selector((state) => state.playback.attack),
        decay: selector((state) => state.playback.decay),
        sustain: selector((state) => state.playback.sustain),
        release: selector((state) => state.playback.release),
        poly: selector((state) => state.playback.poly),
        portamento: selector((state) => state.playback.portamento),
        mouseFlag: selector((state) => state.playback.mouseFlag),
        savedLoop: selector((state) => state.playback.savedLoop),
        pitchLFO: selector((state) => state.playback.pitchLFO),
        pitchLFORate: selector((state) => state.playback.pitchLFORate),
        stepFlag: selector((state) => state.playback.stepFlag),
        splitBands: selector((state) => state.playback.splitBands),
        splitBandFreq: selector((state) => state.playback.splitBandFreq),
        previousVolume: selector((state) => state.playback.previousVolume),
        paused: selector((state) => state.playback.paused),
        seekTo: selector((state) => state.playback.seekTo),
        secondsProgress: selector((state) => state.playback.secondsProgress),
        progress: selector((state) => state.playback.progress),
        dragProgress: selector((state) => state.playback.dragProgress),
        dragging: selector((state) => state.playback.dragging),
        abDragging: selector((state) => state.playback.abDragging)
    }
}

export const usePlaybackActions = () => {
    const dispatch = useDispatch.withTypes<StoreDispatch>()()
    return {
        setReverse: (state: boolean) => dispatch(setReverse(state)),
        setPitch: (state: number) => dispatch(setPitch(state)),
        setSpeed: (state: number) => dispatch(setSpeed(state)),
        setVolume: (state: number) => dispatch(setVolume(state)),
        setMuted: (state: boolean) => dispatch(setMuted(state)),
        setLoop: (state: boolean) => dispatch(setLoop(state)),
        setABLoop: (state: boolean) => dispatch(setABLoop(state)),
        setLoopStart: (state: number) => dispatch(setLoopStart(state)),
        setLoopEnd: (state: number) => dispatch(setLoopEnd(state)),
        setPreservesPitch: (state: boolean) => dispatch(setPreservesPitch(state)),
        setDuration: (state: number) => dispatch(setDuration(state)),
        setSong: (state: string) => dispatch(setSong(state)),
        setSongName: (state: string) => dispatch(setSongName(state)),
        setSongCover: (state: string) => dispatch(setSongCover(state)),
        setSongUrl: (state: string) => dispatch(setSongUrl(state)),
        setEditCode: (state: string) => dispatch(setEditCode(state)),
        setDownload: (state: string) => dispatch(setDownload(state)),
        setPlayHover: (state: boolean) => dispatch(setPlayHover(state)),
        setVolumeHover: (state: boolean) => dispatch(setVolumeHover(state)),
        setSampleRate: (state: number) => dispatch(setSampleRate(state)),
        setReverbMix: (state: number) => dispatch(setReverbMix(state)),
        setReverbDecay: (state: number) => dispatch(setReverbDecay(state)),
        setDelayMix: (state: number) => dispatch(setDelayMix(state)),
        setDelayTime: (state: number) => dispatch(setDelayTime(state)),
        setDelayFeedback: (state: number) => dispatch(setDelayFeedback(state)),
        setPhaserMix: (state: number) => dispatch(setPhaserMix(state)),
        setPhaserFrequency: (state: number) => dispatch(setPhaserFrequency(state)),
        setLowpassCutoff: (state: number) => dispatch(setLowpassCutoff(state)),
        setHighpassCutoff: (state: number) => dispatch(setHighpassCutoff(state)),
        setFilterResonance: (state: number) => dispatch(setFilterResonance(state)),
        setFilterSlope: (state: number) => dispatch(setFilterSlope(state)),
        setHighshelfCutoff: (state: number) => dispatch(setHighshelfCutoff(state)),
        setHighshelfGain: (state: number) => dispatch(setHighshelfGain(state)),
        setLowshelfCutoff: (state: number) => dispatch(setLowshelfCutoff(state)),
        setLowshelfGain: (state: number) => dispatch(setLowshelfGain(state)),
        setMidi: (state: boolean) => dispatch(setMidi(state)),
        setMidiFile: (state: Midi) => dispatch(setMidiFile(state)),
        setMidiDuration: (state: number) => dispatch(setMidiDuration(state)),
        setBpm: (state: number) => dispatch(setBpm(state)),
        setWave: (state: string) => dispatch(setWave(state)),
        setBasicWave: (state: string) => dispatch(setBasicWave(state)),
        setWaveType: (state: string) => dispatch(setWaveType(state)),
        setAttack: (state: number) => dispatch(setAttack(state)),
        setDecay: (state: number) => dispatch(setDecay(state)),
        setSustain: (state: number) => dispatch(setSustain(state)),
        setRelease: (state: number) => dispatch(setRelease(state)),
        setPoly: (state: boolean) => dispatch(setPoly(state)),
        setPortamento: (state: number) => dispatch(setPortamento(state)),
        setMouseFlag: (state: boolean) => dispatch(setMouseFlag(state)),
        setSavedLoop: (state: number[]) => dispatch(setSavedLoop(state)),
        setPitchLFO: (state: boolean) => dispatch(setPitchLFO(state)),
        setPitchLFORate: (state: number) => dispatch(setPitchLFORate(state)),
        setStepFlag: (state: boolean) => dispatch(setStepFlag(state)),
        setSplitBands: (state: boolean) => dispatch(setSplitBands(state)),
        setSplitBandFreq: (state: number) => dispatch(setSplitBandFreq(state)),
        setPreviousVolume: (state: number) => dispatch(setPreviousVolume(state)),
        setPaused: (state: boolean) => dispatch(setPaused(state)),
        setSeekTo: (state: number | null) => dispatch(setSeekTo(state)),
        setSecondsProgress: (state: number) => dispatch(setSecondsProgress(state)),
        setProgress: (state: number) => dispatch(setProgress(state)),
        setDragProgress: (state: number | null) => dispatch(setDragProgress(state)),
        setDragging: (state: boolean) => dispatch(setDragging(state)),
        setABDragging: (state: boolean) => dispatch(setABDragging(state))
    }
}

export default playbackSlice.reducer